// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARZg6cUGaXBO1k6QqxOa9Pk3Nx2AIMNnU',
    appId: '1:216440272302:web:26d1a85407e00fb344443f',
    messagingSenderId: '216440272302',
    projectId: 'messmate-2026-shazid',
    authDomain: 'messmate-2026-shazid.firebaseapp.com',
    storageBucket: 'messmate-2026-shazid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3mMHfOIBWjeI1lg1ObRb7o255VVKUDtI',
    appId: '1:216440272302:android:92d01d2fc7de3a4c44443f',
    messagingSenderId: '216440272302',
    projectId: 'messmate-2026-shazid',
    storageBucket: 'messmate-2026-shazid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHDZFdTq8G6G8DsPCX070kEZmtlai7FI',
    appId: '1:216440272302:ios:b631c6983b4ef94e44443f',
    messagingSenderId: '216440272302',
    projectId: 'messmate-2026-shazid',
    storageBucket: 'messmate-2026-shazid.firebasestorage.app',
    iosBundleId: 'com.example.messmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJHDZFdTq8G6G8DsPCX070kEZmtlai7FI',
    appId: '1:216440272302:ios:b631c6983b4ef94e44443f',
    messagingSenderId: '216440272302',
    projectId: 'messmate-2026-shazid',
    storageBucket: 'messmate-2026-shazid.firebasestorage.app',
    iosBundleId: 'com.example.messmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARZg6cUGaXBO1k6QqxOa9Pk3Nx2AIMNnU',
    appId: '1:216440272302:web:706e34ebf36a51cc44443f',
    messagingSenderId: '216440272302',
    projectId: 'messmate-2026-shazid',
    authDomain: 'messmate-2026-shazid.firebaseapp.com',
    storageBucket: 'messmate-2026-shazid.firebasestorage.app',
  );
}
